
menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  标签: { id: tags, url: /tags }
  分类: { id: categories, url: /categories }
  关于: { id: curriculumvitae, url: /about}
  RSS: { id: rss, url: /atom.xml }
  # 链接: { id: links, url: /links }
github: FloatingGuy
background-root: /images/background/
background: [
  0.jpg,
  1.jpg,
  2.jpg,
  3.jpg,
  4.jpg,
  5.jpg,
  6.jpg,
  7.jpg,
  8.jpg,
  9.jpg,
  10.jpg,
  11.jpg,
  12.jpg,
  13.jpg,
  14.jpg,
  15.jpg,
  16.jpg,
  17.jpg, ]

avatar: /images/china.gif
 # /images/avatar.gif

#### Comment
duoshuo:
  short_name: floatingguy  ## duoshuo short name.
                                         ## refer to http://dev.duoshuo.com/docs/501e6ce1cff715f71800000d

rss: /atom.xml                   ## if any...